Update github actions (#67)
* run based on labels
* fix names, make nice

diff --git a/.github/workflows/merge_json_files.yaml b/.github/workflows/merge_json_files.yaml
--- a/.github/workflows/merge_json_files.yaml
+++ b/.github/workflows/merge_json_files.yaml
@@ -1,8 +1,11 @@
 name: Merge JSON files
-
+env:
+  LABEL: 'BIP JSON'
 on:
   pull_request:
-    types: [closed]
+    types: [ closed ]
+    branches: [ main ]
+
 
 jobs:
   merge_json:
@@ -10,9 +13,28 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code (PR)
+        if: steps.BIPJSON.outputs.hasLabel == 'true'
         uses: actions/checkout@v3
         with:
-           path: pr
+          path: pr
+
+      - name: Check Label
+        run: |
+          if [ "$GITHUB_EVENT_NAME" == "pull_request" ]; then
+            echo "Checking for label '${{ env.LABEL }}' on the pull request associated with commit '$GITHUB_SHA'"
+            pull_request_labels=$(jq --raw-output '.pull_request.labels[].name' "$GITHUB_EVENT_PATH")
+            if echo "$pull_request_labels" | grep -q '${{ env.LABEL }}'; then
+              echo "Label '${{ env.LABEL }}' found on pull request"
+            else
+              echo "Label '${{ env.LABEL }} not found on pull request"
+              echo "Exiting action"
+              exit 1
+            fi
+          else
+            echo "No pull request associated with commit '$GITHUB_SHA'"
+            echo "Exiting action"
+            exit 1
+          fi
 
       - name: Checkout main branch for combined jsons
         uses: actions/checkout@v3
diff --git a/.github/workflows/run_auth_gen.yaml b/.github/workflows/run_auth_gen.yaml
--- a/.github/workflows/run_auth_gen.yaml
+++ b/.github/workflows/run_auth_gen.yaml
@@ -1,4 +1,4 @@
-name: Generate new Authorizer payloads if Generate Authorizer is labeled and input file is in the right place
+name: Generate new Authorizer Payloads
 
 on:
   pull_request:
@@ -6,6 +6,7 @@ on:
 
 env:
   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  LABEL: "Generate Authorizer"
 
 jobs:
   gen_auth:
@@ -14,24 +15,36 @@ jobs:
       run:
         working-directory: tools/python
     steps:
-    - uses: Dreamcodeio/pr-has-label-action@master
-      id: checkLabel
-      with:
-        label: 'Generate Authorizer'
-    - uses: actions/checkout@v2
+    - name: Checkout
+      uses: actions/checkout@v2
+
+    - name: Check label
+      run: |
+        if [ "$GITHUB_EVENT_NAME" == "pull_request" ]; then
+          echo "Checking for label '${{ env.LABEL }}' on the pull request associated with commit '$GITHUB_SHA'"
+          pull_request_labels=$(jq --raw-output '.pull_request.labels[].name' "$GITHUB_EVENT_PATH")
+          if echo "$pull_request_labels" | grep -q '${{ env.LABEL }}'; then
+            echo "Label '${{ env.LABEL }}' found on pull request"
+          else
+            echo "Label '${{ env.LABEL }} not found on pull request"
+            echo "Exiting action"
+            exit 1
+          fi
+        else
+          echo "No pull request associated with commit '$GITHUB_SHA'"
+          echo "Exiting action"
+          exit 1
+        fi
 
     - name: Setup Python 3.9
       uses: actions/setup-python@v2
       with:
         python-version: 3.9
 
-    - name: print working dir
-      run: pwd
-
     - name: Install Requirements
       run: pip install -r requirements.txt
 
-    - name: Run Sweep
+    - name: Do Work
       run: python3 gen_add_permissions_payload.py
 
     - name: Commit and push changes
diff --git a/.github/workflows/run_feesweep.yaml b/.github/workflows/run_feesweep.yaml
--- a/.github/workflows/run_feesweep.yaml
+++ b/.github/workflows/run_feesweep.yaml
@@ -1,29 +1,45 @@
-name: Run Sweep Fees if new input data is there
+name: Generate feeSweep payloads
 
 on:
   pull_request:
-    types: [ labeled ]
+    types: [ labeled, synchronize ]
 
 env:
   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  LABEL: Sweep Fees
 
 jobs:
   sweepFees:
-    if: github.event.label.name == 'Sweep Fees'
     runs-on: ubuntu-latest
     defaults:
       run:
         working-directory: tools/python
     steps:
-    - uses: actions/checkout@v2
+    - name: Checkout
+      uses: actions/checkout@v2
 
+    - name: Check label
+      run: |
+        if [ "$GITHUB_EVENT_NAME" == "pull_request" ]; then
+          echo "Checking for label '${{ env.LABEL }}' on the pull request associated with commit '$GITHUB_SHA'"
+          pull_request_labels=$(jq --raw-output '.pull_request.labels[].name' "$GITHUB_EVENT_PATH")
+          if echo "$pull_request_labels" | grep -q '${{ env.LABEL }}'; then
+            echo "Label '${{ env.LABEL }}' found on pull request"
+          else
+            echo "Label '${{ env.LABEL }} not found on pull request"
+            echo "Exiting action"
+            exit 1
+          fi
+        else
+          echo "No pull request associated with commit '$GITHUB_SHA'"
+          echo "Exiting action"
+          exit 1
+        fi
+    
     - name: Setup Python 3.9
       uses: actions/setup-python@v2
       with:
         python-version: 3.9
-
-    - name: print working dir
-      run: pwd
 
     - name: Install Requirements
       run: pip install -r requirements.txt
