switch to using bash script method for label detection.

diff --git a/.github/workflows/merge_json_files.yaml b/.github/workflows/merge_json_files.yaml
--- a/.github/workflows/merge_json_files.yaml
+++ b/.github/workflows/merge_json_files.yaml
@@ -1,5 +1,6 @@
 name: Merge JSON files
-
+env:
+  LABEL: 'BIP JSON'
 on:
   pull_request:
     types: [ closed ]
@@ -13,8 +14,20 @@ jobs:
     steps:
       - uses: Dreamcodeio/pr-has-label-action@master
         id: 'BIP JSON'
-        with:
-          label: 'BIPJSON'
+        run: |
+          echo "Checking for label '${{ env.LABEL }}' on the pull request associated with commit '${{ github.sha }}'"
+          COMMIT_PULL_REQUEST_NUMBER=$(curl -s https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/pulls?state=all | jq --raw-output '.[0].number')
+          if [[ $COMMIT_PULL_REQUEST_NUMBER == null ]]; then
+            echo "No pull request associated with commit '${{ github.sha }}'"
+            exit 78
+          fi
+          LABEL_EXISTS=$(curl -s https://api.github.com/repos/${{ github.repository }}/pulls/$COMMIT_PULL_REQUEST_NUMBER/labels | jq --raw-output 'map(.name) | index("${{ env.LABEL }}")')
+          if [[ $LABEL_EXISTS == null ]]; then
+            echo "Label '${{ env.LABEL }}' not found on pull request $COMMIT_PULL_REQUEST_NUMBER"
+            exit 78
+          fi
+          echo "Label '${{ env.LABEL }}' found on pull request $COMMIT_PULL_REQUEST_NUMBER"
+
       - name: Checkout code (PR)
         if: steps.BIPJSON.outputs.hasLabel == 'true'
         uses: actions/checkout@v3
diff --git a/.github/workflows/run_auth_gen.yaml b/.github/workflows/run_auth_gen.yaml
--- a/.github/workflows/run_auth_gen.yaml
+++ b/.github/workflows/run_auth_gen.yaml
@@ -6,6 +6,7 @@ on:
 
 env:
   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  LABEL: "Generate Authorizer"
 
 jobs:
   gen_auth:
@@ -16,9 +17,19 @@ jobs:
     steps:
     - name: Check label
       uses: Dreamcodeio/pr-has-label-action@master
-      id: genAuth
-      with:
-        label: 'Generate Authorizer'
+      run: |
+        echo "Checking for label '${{ env.LABEL }}' on the pull request associated with commit '${{ github.sha }}'"
+        COMMIT_PULL_REQUEST_NUMBER=$(curl -s https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/pulls?state=all | jq --raw-output '.[0].number')
+        if [[ $COMMIT_PULL_REQUEST_NUMBER == null ]]; then
+          echo "No pull request associated with commit '${{ github.sha }}'"
+          exit 78
+        fi
+        LABEL_EXISTS=$(curl -s https://api.github.com/repos/${{ github.repository }}/pulls/$COMMIT_PULL_REQUEST_NUMBER/labels | jq --raw-output 'map(.name) | index("${{ env.LABEL }}")')
+        if [[ $LABEL_EXISTS == null ]]; then
+          echo "Label '${{ env.LABEL }}' not found on pull request $COMMIT_PULL_REQUEST_NUMBER"
+          exit 78
+        fi
+        echo "Label '${{ env.LABEL }}' found on pull request $COMMIT_PULL_REQUEST_NUMBER"
 
     - name: Checkout
       uses: actions/checkout@v2
