test bash script to better handle label check.

diff --git a/.github/workflows/run_feesweep.yaml b/.github/workflows/run_feesweep.yaml
--- a/.github/workflows/run_feesweep.yaml
+++ b/.github/workflows/run_feesweep.yaml
@@ -6,7 +6,7 @@ on:
 
 env:
   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-
+  LABEL: Sweep Fees
 jobs:
   sweepFees:
     runs-on: ubuntu-latest
@@ -14,14 +14,25 @@ jobs:
       run:
         working-directory: tools/python
     steps:
-    - uses: Dreamcodeio/pr-has-label-action@master
+    - name: Check Label
       id: doFeeSweep
-      with:
-        label: 'Generate Authorizer'
+      run: |
+        echo "Checking for label '${{ env.LABEL }}' on the pull request associated with commit '${{ github.sha }}'"
+        COMMIT_PULL_REQUEST_NUMBER=$(curl -s https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/pulls?state=all | jq --raw-output '.[0].number')
+        if [[ $COMMIT_PULL_REQUEST_NUMBER == null ]]; then
+          echo "No pull request associated with commit '${{ github.sha }}'"
+          exit 78
+        fi
+        LABEL_EXISTS=$(curl -s https://api.github.com/repos/${{ github.repository }}/pulls/$COMMIT_PULL_REQUEST_NUMBER/labels | jq --raw-output 'map(.name) | index("${{ env.LABEL }}")')
+        if [[ $LABEL_EXISTS == null ]]; then
+          echo "Label '${{ env.LABEL }}' not found on pull request $COMMIT_PULL_REQUEST_NUMBER"
+          exit 78
+        fi
+        echo "Label '${{ env.LABEL }}' found on pull request $COMMIT_PULL_REQUEST_NUMBER"
+    
 
     - name: checkout
       uses: actions/checkout@v2
-      if: steps.doFeeSweep.outputs.hasLabel == 'true'
 
     - name: Setup Python 3.9
       uses: actions/setup-python@v2
