Try another method to see if the commit is to a pr with a label.

diff --git a/.github/workflows/run_auth_gen.yaml b/.github/workflows/run_auth_gen.yaml
--- a/.github/workflows/run_auth_gen.yaml
+++ b/.github/workflows/run_auth_gen.yaml
@@ -20,18 +20,20 @@ jobs:
 
     - name: Check label
       run: |
-        echo "Checking for label '${{ env.LABEL }}' on the pull request associated with commit '${{ github.sha }}'"
-        COMMIT_PULL_REQUEST_NUMBER=$(curl -s https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/pulls?state=all | jq --raw-output '.[0].number')
-        if [[ $COMMIT_PULL_REQUEST_NUMBER == null ]]; then
-          echo "No pull request associated with commit '${{ github.sha }}'"
-          exit 78
-        fi
-        LABEL_EXISTS=$(curl -s https://api.github.com/repos/${{ github.repository }}/pulls/$COMMIT_PULL_REQUEST_NUMBER/labels | jq --raw-output 'map(.name) | index("${{ env.LABEL }}")')
-        if [[ $LABEL_EXISTS == null ]]; then
-          echo "Label '${{ env.LABEL }}' not found on pull request $COMMIT_PULL_REQUEST_NUMBER"
-          exit 78
-        fi
-        echo "Label '${{ env.LABEL }}' found on pull request $COMMIT_PULL_REQUEST_NUMBER"
+        if [ "$GITHUB_EVENT_NAME" == "pull_request" ]; then
+          echo "Checking for label 'Generate Authorizer' on the pull request associated with commit '$GITHUB_SHA'"
+          pull_request_labels=$(jq --raw-output '.pull_request.labels[].name' "$GITHUB_EVENT_PATH")
+          if echo "$pull_request_labels" | grep -q "Generate Authorizer"; then
+            echo "Label 'Generate Authorizer' found on pull request"
+          else
+            echo "Label 'Generate Authorizer' not found on pull request"
+            echo "Exiting action"
+            exit 1
+          fi
+        else
+          echo "No pull request associated with commit '$GITHUB_SHA'"
+          echo "Exiting action"
+          exit 1
 
     - name: Setup Python 3.9
       uses: actions/setup-python@v2
